import { Location } from "@/agents/types";

export const WORLD_LOCATIONS: Location[] = [
  {
    id: "solana-hq",
    name: "Solana HQ",
    description: "The main Solana Labs headquarters. Engineers work on protocol upgrades and core infrastructure here.",
    x: 400,
    y: 100,
    width: 160,
    height: 120,
    type: "building",
  },
  {
    id: "drip-gallery",
    name: "DRiP Gallery",
    description: "A vibrant gallery showcasing digital collectibles and compressed NFT art from creators around the world.",
    x: 100,
    y: 100,
    width: 120,
    height: 100,
    type: "building",
  },
  {
    id: "colosseum",
    name: "The Colosseum",
    description: "A grand arena where hackathon teams form, projects are pitched, and builders compete for prizes.",
    x: 250,
    y: 300,
    width: 180,
    height: 140,
    type: "building",
  },
  {
    id: "helius-labs",
    name: "Helius Labs",
    description: "The Helius RPC infrastructure lab. Monitors, dashboards, and servers tracking Solana network health.",
    x: 600,
    y: 100,
    width: 120,
    height: 100,
    type: "building",
  },
  {
    id: "dev-hub",
    name: "Dev Hub",
    description: "An open workspace where developers build with Anchor, test programs, and collaborate on open source tools.",
    x: 600,
    y: 300,
    width: 140,
    height: 120,
    type: "building",
  },
  {
    id: "learning-center",
    name: "Learning Center",
    description: "Workshops, tutorials, and documentation sessions for new Solana developers.",
    x: 100,
    y: 400,
    width: 120,
    height: 100,
    type: "building",
  },
  {
    id: "town-square",
    name: "Town Square",
    description: "The central gathering place where agents meet, chat, and share the latest Solana news.",
    x: 350,
    y: 200,
    width: 100,
    height: 80,
    type: "outdoor",
  },
  {
    id: "press-room",
    name: "Press Room",
    description: "Media and communications center inside Solana HQ for interviews and announcements.",
    x: 450,
    y: 50,
    width: 80,
    height: 60,
    type: "building",
  },
  {
    id: "cafe",
    name: "Validators' Café",
    description: "A cozy café where agents grab coffee, have casual conversations, and brainstorm ideas.",
    x: 500,
    y: 450,
    width: 100,
    height: 80,
    type: "building",
  },
  {
    id: "park",
    name: "Consensus Park",
    description: "A peaceful park for walks and reflection. Agents come here to think deeply and plan their next moves.",
    x: 100,
    y: 250,
    width: 120,
    height: 100,
    type: "outdoor",
  },
];
