import { Location } from "@/agents/types";

export const WORLD_LOCATIONS: Location[] = [
  {
    id: "solana-hq",
    name: "Solana HQ",
    description: "The main Solana Labs headquarters. Engineers work on protocol upgrades and core infrastructure here.",
    x: 250,
    y: 15,
    width: 90,
    height: 68,
    type: "building",
  },
  {
    id: "drip-gallery",
    name: "DRiP Gallery",
    description: "A vibrant gallery showcasing digital collectibles and compressed NFT art from creators around the world.",
    x: 15,
    y: 15,
    width: 75,
    height: 60,
    type: "building",
  },
  {
    id: "colosseum",
    name: "The Colosseum",
    description: "A grand arena where hackathon teams form, projects are pitched, and builders compete for prizes.",
    x: 175,
    y: 215,
    width: 98,
    height: 75,
    type: "building",
  },
  {
    id: "helius-labs",
    name: "Helius Labs",
    description: "The Helius RPC infrastructure lab. Monitors, dashboards, and servers tracking Solana network health.",
    x: 380,
    y: 15,
    width: 80,
    height: 60,
    type: "building",
  },
  {
    id: "dev-hub",
    name: "Dev Hub",
    description: "An open workspace where developers build with Anchor, test programs, and collaborate on open source tools.",
    x: 375,
    y: 215,
    width: 82,
    height: 68,
    type: "building",
  },
  {
    id: "learning-center",
    name: "Learning Center",
    description: "Workshops, tutorials, and documentation sessions for new Solana developers.",
    x: 15,
    y: 280,
    width: 75,
    height: 60,
    type: "building",
  },
  {
    id: "town-square",
    name: "Town Square",
    description: "The central gathering place where agents meet, chat, and share the latest Solana news.",
    x: 195,
    y: 110,
    width: 70,
    height: 55,
    type: "outdoor",
  },
  {
    id: "press-room",
    name: "Press Room",
    description: "Media and communications center inside Solana HQ for interviews and announcements.",
    x: 130,
    y: 15,
    width: 68,
    height: 50,
    type: "building",
  },
  {
    id: "cafe",
    name: "Validators' Café",
    description: "A cozy café where agents grab coffee, have casual conversations, and brainstorm ideas.",
    x: 310,
    y: 300,
    width: 68,
    height: 48,
    type: "building",
  },
  {
    id: "park",
    name: "Consensus Park",
    description: "A peaceful park for walks and reflection. Agents come here to think deeply and plan their next moves.",
    x: 15,
    y: 130,
    width: 80,
    height: 65,
    type: "outdoor",
  },
];
